### ISSUE TITLE
error after sending link instagram

### ISSUE THREAD

**Issue by iCesenberk** [andrewwang84/94Orig#3]
![asdasdasd](https://user-images.githubusercontent.com/60349856/76141044-49a17b00-6093-11ea-8431-657a8b7c73f4.PNG)

**Comment by andrewwang84** [comment]
please check your heroku local var setting

**Comment by iCesenberk** [comment]
Is there anything wrong?
![Capture](https://user-images.githubusercontent.com/60349856/76154539-924b4980-6110-11ea-80c2-83e94d3f4517.PNG)

**Comment by andrewwang84** [comment]
try this https://teleig.herokuapp.com/

**Comment by iCesenberk** [comment]
it works. Thanks
![Capture](https://user-images.githubusercontent.com/60349856/76217748-8f9e4080-6245-11ea-8c6a-08bffd84e576.PNG)
