### ISSUE TITLE
API Deprecated for Telegram Bot

### ISSUE THREAD

**Issue by RobertMakeev07** [andrewwang84/94Orig#8]
Right now it is working on your Website, but when I send an Instagram Post or Account link to Telegram Bot, it says API Deprecated. Please adjust the configuration as in past, it should send downloadable links.
[Here is My Telegram Bot](https://t.me/robertssocialdownloaderbot)

**Comment by andrewwang84** [comment]
I don't really get it, it seems that you've already deploy it on your own site. Why don't you just switch your API endpoint to your own site?

Wish to can provide you the API for free. However, I do not have so much money to maintain the server.  If this project did help you, I will appreciate for your donation.

https://paypal.me/yrwwwww
