### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by RobertMakeev07** [andrewwang84/94Orig#9]
I have tested your code months ago and days ago again attempted to make it work but in vain. It worked fine in my localhost when I pushed the code to the server (Heroku), it did not work until I added config vars (telegramToken and url). I put the URL = your website link and it worked fine, but when I changed it to my deployed website, it is not working. I don't know what is wrong. In local is fine, when I push the code on the server, it is not working.

**Comment by andrewwang84** [comment]
What's your url format?
try [https://robertssocialdownloadertool.herokuapp.com] 

BTW maybe try upgrade to latest commit, and API will only be needed by web interface, bots will execute direct function call now

**Comment by RobertMakeev07** [comment]
> What's your url format?
> try [https://robertssocialdownloadertool.herokuapp.com]
> 
> BTW maybe try upgrade to latest commit, and API will only be needed by web interface, bots will execute direct function call now
